### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by MiiRaGe** [novopl/peltak#1]
Traceback (most recent call last):
  File "/usr/local/bin/peltak", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/peltak/runner.py", line 107, in main
    app = AppContext(cl)
  File "/usr/local/lib/python3.4/site-packages/peltak/system/appcontext.py", line 29, in __init__
    self.load_config()
  File "/usr/local/lib/python3.4/site-packages/peltak/system/appcontext.py", line 34, in load_config
    if url.path.endswith('.git'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

**Comment by novopl** [comment]
Fixed
